[package]
name = "spars-httpd"
version = "0.0.1"
authors = ["Cullen Walsh <ckwalsh@cullenwalsh.com>"]
edition = "2024"
rust-version = "1.85.1"
description = "A small httpd for serving static files and SPAs"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ckwalsh/spars"
keywords = ["httpd"]
categories = ["command-line-utilities", "web-programming"]
include = [
  "/src",
  "/Cargo.lock",
  "/Cargo.toml",
  "/LICENSE-APACHE",
  "/LICENSE-MIT",
  "/README.md",
  "/rust-toolchain.toml",
]

[profile.release]
strip = "symbols"
lto = "fat"

[profile.plaid]
inherits = "release"
opt-level = "z"
panic = "abort"
codegen-units = 1

[features]
default = []
mime_guess = ["dep:mime_guess"]
signal-hook = ["dep:signal-hook"]

[dependencies]
arrayvec = "0.7.6"
async-executor = "1.13.2"
async-io = "2.5.0"
blocking = "1.6.2"
compact_str = "0.9.0"
futures-lite = "2.6.1"
httparse = "1.10.1"
mime_guess = { version = "2.0.5", optional = true }
signal-hook = { version = "0.3.18", optional = true }
thiserror = "2.0.15"
zerotrie = { version = "0.2.2", features = ["alloc"] }

[dev-dependencies]
futures-util = "0.3.31"
http = "1.3.1"
http-body-util = "0.1.3"
hyper = { version = "1.7.0", features = ["http1", "server"], default-features = false }
hyper-util = { version = "0.1.16", features = ["http1", "server"], default-features = false }
reqwest = { version = "0.12.23", features = ["blocking"], default-features = false }
tempfile = "3.21.0"
tokio = { version = "1.47.1", features = ["fs", "macros", "rt-multi-thread"], default-features = false }
tokio-util = { version = "0.7.16", features = ["io"], default-features = false }
