name: CI

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0

defaults:
  run:
    shell: bash

jobs:
  stable:
    runs-on: default
    steps:
      - run: sudo apt-get update && sudo apt-get install -y build-essential
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: x86_64-unknown-linux-gnu

      # Lint
      - run: cargo fmt --all --check
      - run: cargo clippy --all-features --all-targets

      # default features build
      - run: cargo build --all
      - run: cargo test

      # mime_guess build
      - run: cargo build --all --features mime_guess
      - run: cargo test --features mime_guess

  plaid:
    runs-on: default
    needs: stable
    env:
      RUST_TOOLCHAIN: nightly-2025-08-18
      RUST_TARGET: x86_64-unknown-linux-musl
    steps:
      - run: sudo apt-get update && sudo apt-get install -y build-essential
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rust-src
          targets: ${{ env.RUST_TARGET }}
      - run:
          cargo "+$RUST_TOOLCHAIN" build --bins --examples --profile plaid
          --target "$RUST_TARGET" -Z build-std="std,panic_abort" -Z
          build-std-features="optimize_for_size,panic_immediate_abort"

  docker:
    runs-on: default
    needs: stable
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          push: false
